### ISSUE TITLE
Length must be between {min} and {max}

### ISSUE THREAD

**Issue by TomerTcherniak** [OpenVPN/terraform-provider-openvpn-cloud#105]
why do i have the below error when running terraform apply

openvpncloud_network.network: Refreshing state... [id=456b91d2-5755-4acd-8247-61494ba40247]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # openvpncloud_network.network will be updated in-place
  ~ resource "openvpncloud_network" "network" {
      + description     = "Managed by Terraform"
        id              = "456b91d2-5755-4acd-8247-61494ba40247"
      ~ name            = "sss" -> "Sss"
        # (3 unchanged attributes hidden)

      + default_connector {
          + name          = "test-connector"
          + vpn_region_id = "eu-central-1"
        }

      + default_route {
          + type  = "IP_V4"
          + value = "192.198.0.0/32"
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

openvpncloud_network.network: Modifying... [id=456b91d2-5755-4acd-8247-61494ba40247]
╷
│ Error: Status code: 400, Response body: {"errorDetails":{"description":[{"errorCode":"0-10-25","message":"Length must be between {min} and {max}"}]},"errorMessage":"Request validation failed","path":"/api/beta/networks/456b91d2-5755-4acd-8247-61494ba40247/routes","requestId":"281deeb3-91","status":400,"statusError":"Bad Request","timestamp":1697129387334}
│ 
│   with openvpncloud_network.network,
│   on main.tf line 18, in resource "openvpncloud_network" "network":
│   18: resource "openvpncloud_network" "network" {

**Comment by sahaqaa** [comment]
We've published new version of Terraform Provider to Registry: https://registry.terraform.io/providers/OpenVPN/cloudconnexa/latest

Going forward only https://registry.terraform.io/providers/OpenVPN/cloudconnexa/latest will be developed.

Please give new provider a try, hopefully it will fix your issue.

In case if problem persists - please open new "Issue" (https://github.com/OpenVPN/terraform-provider-cloudconnexa/issues)

Sorry for inconvenience.
