### ISSUE TITLE
0.0.11 will not initialize

### ISSUE THREAD

**Issue by sinkr** [OpenVPN/terraform-provider-openvpn-cloud#107]
Seems to be a mismatch between resource names.  I had to revert to 0.0.7 to get things like `openvpncloud_network` to apply correctly.

**provider.tf**
```
terraform {
  required_version = ">= 1.1.5"
  required_providers {
    openvpn-cloud = {
      source  = "OpenVPN/openvpn-cloud"
      version = "0.0.11"
    }
  }
}

provider "openvpn-cloud" {
  base_url = "https://MYDOMAIN.api.openvpn.com"
}
```

**main.tf**
```
resource "openvpncloud_network" "development" {
  name   = "Development"
  egress = false
  default_route {
    value = "10.0.0.0/12"
  }
  default_connector {
    name          = "development01"
    vpn_region_id = "eu-central-1"
  }
}
```

**terraform init**
```
Initializing the backend...

Initializing provider plugins...
- Reusing previous version of openvpn/openvpn-cloud from the dependency lock file
- Finding latest version of hashicorp/openvpncloud...

- Using previously-installed openvpn/openvpn-cloud v0.0.11
╷
│ Error: Failed to query available provider packages
│
│ Could not retrieve the list of available versions for provider hashicorp/openvpncloud: provider registry registry.terraform.io does
│ not have a provider named registry.terraform.io/hashicorp/openvpncloud
│
│ All modules should specify their required_providers so that external consumers will get the correct providers when using a module.
│ To see which modules are currently depending on hashicorp/openvpncloud, run the following command:
│     terraform providers
```

**Comment by maciej-elisity** [comment]
https://github.com/OpenVPN/terraform-provider-openvpn-cloud/issues/18#issuecomment-1403968165

**Comment by d1rtym0nk3y** [comment]
the linked issue is marked as closed, but theres no new release and this is still very broken

**Comment by pickgr** [comment]
There are discrepancies in the documentation between the provider name and resource names. See https://github.com/OpenVPN/terraform-provider-openvpn-cloud/issues/18#issuecomment-1403968165

**Comment by sahaqaa** [comment]
We've published new version of Terraform Provider to Registry: https://registry.terraform.io/providers/OpenVPN/cloudconnexa/latest

Going forward only https://registry.terraform.io/providers/OpenVPN/cloudconnexa/latest will be developed.

Please give new provider a try, hopefully it will fix your issue.

In case if problem persists - please open new "Issue" (https://github.com/OpenVPN/terraform-provider-cloudconnexa/issues)

Sorry for inconvenience.
