### ISSUE TITLE
Add Support for Application Resource in OpenVPN Cloud Terraform Provider

### ISSUE THREAD

**Issue by smantzou** [OpenVPN/terraform-provider-openvpn-cloud#114]
Hello,

I'm currently using your Terraform provider for OpenVPN Cloud and it's been very helpful. However, I've noticed that the provider currently does not support the Application resource.

The Application resource is crucial for managing applications in OpenVPN Cloud. It would be very beneficial if the provider could support creating, reading, updating, and deleting Application resources.

Here are some of the key attributes that an Application resource should have:

- Name
- Description
- Routes
- Config (including custom service types and service types)

I believe adding this feature would greatly enhance the functionality of the provider and make it even more useful for managing OpenVPN Cloud resources.

Thank you for considering this feature request. I'm looking forward to seeing this feature in a future release.

Best regards,
   smantzou

**Comment by sahaqaa** [comment]
We've published new version of Terraform Provider to Registry: https://registry.terraform.io/providers/OpenVPN/cloudconnexa/latest

Going forward only https://registry.terraform.io/providers/OpenVPN/cloudconnexa/latest will be developed.

Please give new provider a try, hopefully it will fix your issue.

In case if problem persists - please open new "Issue" (https://github.com/OpenVPN/terraform-provider-cloudconnexa/issues)

Sorry for inconvenience.
