### ISSUE TITLE
Network with empty routes produces 404 error

### ISSUE THREAD

**Issue by chornns** [OpenVPN/terraform-provider-openvpn-cloud#12]
If a network with no routes is iterated before the network with the route being imported or updated, a 404 error is produced:
```
aws_route53_record.record: Refreshing state... [id=Z06558302SO4GX058CO2F_platform-database.sct-prd-west.nowsecure.io._CNAME]
╷
│ Error: Status code: 404, Response body: []
│ 
│   with openvpncloud_route.ops,
│   on main.tf line 152, in resource "openvpncloud_route" "ops":
│  152: resource "openvpncloud_route" "ops" {

```

While it is reasonable for `api/beta/networks/%s/routes` to return a 404 when a specific network has no routes, it seems less reasonable for that error to be treated as fatal:
https://github.com/OpenVPN/terraform-provider-openvpn-cloud/blob/9346cb3e36a3d632ac05a0f9b31e8b72694f1b90/client/route.go#L103

**Comment by michaelfmnk** [comment]
Hey! @chornns Does the issue still persist?

**Comment by chornns** [comment]
This is a bit disruptive to test, but I don't see why a description on a default route would help when the situation described is a network without any routes.

**Comment by sahaqaa** [comment]
We've published new version of Terraform Provider to Registry: https://registry.terraform.io/providers/OpenVPN/cloudconnexa/latest

Going forward only https://registry.terraform.io/providers/OpenVPN/cloudconnexa/latest will be developed.

Please give new provider a try, hopefully it will fix your issue.

In case if problem persists - please open new "Issue" (https://github.com/OpenVPN/terraform-provider-cloudconnexa/issues)

Sorry for inconvenience.
