### ISSUE TITLE
Request for ".ovpn Profile Token" attribute for the openvpncloud_connector resource

### ISSUE THREAD

**Issue by pickgr** [OpenVPN/terraform-provider-openvpn-cloud#126]
I'm trying to fully automate the provisioning of a network and its associated routes and connectors via terraform, including the management of the EC2 instances and other resources in AWS.

The only piece I'm missing is the ability to read the ".ovpn Profile Token" from the `openvpncloud_connector` resource which is used in the EC2 user_data cloudinit script. Currently, this has to be copied from the UI. I'm not sure if the API supports it, but it's not listed as a read-only attribute here:

https://registry.terraform.io/providers/OpenVPN/openvpn-cloud/latest/docs/resources/connector

Ideally, it would also need to be available from the "default connector" for the `openvpncloud_network` resource:

https://registry.terraform.io/providers/OpenVPN/openvpn-cloud/latest/docs/resources/network

As potentially another improvement, I think it would be better if the "default connector" was not mandatory and these could be managed completely independently in the individual `openvpncloud_connector` resource. Same for the "default_route"

**Comment by arslanbekov** [comment]
@pickgr Hi! The [API has such functionality](https://openvpn.net/cloud-docs/developer/cloudconnexa-api/connector/generate--ovpn-profile-token-for-an-existing-connector.html) but has not yet been implemented in this provider.

JFYI: The API has changed a lot, and the provider in the current implementation does not seem to be fully working. We are actively working on supporting the new version of the API, and I will keep you informed.

There, we will immediately add the ability to receive a profile from the connector.

**Comment by bwesolowskicf** [comment]
@arslanbekov That's great news!
We're currently implementing the latest version of this provider and found a few key things missing, as others have pointed out in this and other tickets here.

Would you be able to provide any (even rough) estimate on when could we expect a new version?

**Comment by arslanbekov** [comment]
@bwesolowskicf Hi, thanks! I believe we can release this month.

**Comment by pickgr** [comment]
>  Hi, thanks! I believe we can release this month.

@arslanbekov can you please give an update on when a new version will be released? This project seems to have gone stale.

**Comment by chicco785** [comment]
I made changes to retrieve profile, but not yet for the token: https://github.com/OpenVPN/terraform-provider-openvpn-cloud/pull/136

**Comment by sahaqaa** [comment]
We've published new version of Terraform Provider to Registry: https://registry.terraform.io/providers/OpenVPN/cloudconnexa/latest

Going forward only https://registry.terraform.io/providers/OpenVPN/cloudconnexa/latest will be developed.

Please give new provider a try, hopefully it will fix your issue.

In case if problem persisst - please open new "Issue" (https://github.com/OpenVPN/terraform-provider-cloudconnexa/issues)

Sorry for inconvenience.
