### ISSUE TITLE
not working anymore?

### ISSUE THREAD

**Issue by chicco785** [OpenVPN/terraform-provider-openvpn-cloud#130]
currently if i try to deploy a resource i get: 

```
│   35: provider "openvpncloud" {
│ 
│ Error: invalid character '<' looking for beginning of value
```

most probably something changed in the api?

**Comment by sahaqaa** [comment]
Hello, kindly please provide code how you initialize provider and code which you are using to create resource? (if resource that you are trying to create depends on another resource -> please provide all needed code to reproduce issue)

**Comment by chicco785** [comment]
> Hello, kindly please provide code how you initialize provider and code which you are using to create resource? (if resource that you are trying to create depends on another resource -> please provide all needed code to reproduce issue)

for now I solved by adding fixes to the client and the provider: https://github.com/OpenVPN/terraform-provider-openvpn-cloud/pull/136
