### ISSUE TITLE
API throttling (Error: Status code: 429, Response body:)

### ISSUE THREAD

**Issue by pickgr** [OpenVPN/terraform-provider-openvpn-cloud#131]
I've recently started seeing errors like this. Presumably, we are getting throttled by the Connexa API.

I'm curious if anyone else has run into this and if there are any work-arounds?  I'll also create a Connexa support ticket as this is probably not strictly a terraform-related issue.

```
Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: Status code: 429, Response body:
│
│   with module.openvpn-cloud.openvpncloud_host.this["foo"],
│   on ../../modules/openvpn-cloud/hosts.tf line 1, in resource "openvpncloud_host" "this":
│    1: resource "openvpncloud_host" "this" {
│
╵
Releasing state lock. This may take a few moments...
```

**Comment by pickgr** [comment]
For reference: https://support.openvpn.com/hc/en-us/requests/496093

**Comment by pickgr** [comment]
Per Connexa support:

```
x-ratelimit-burst-capacity: 20 
x-ratelimit-replenish-rate: 1 
x-ratelimit-replenish-time: 15 seconds
```

are the default rate limits.

These can be increased, but it is not a quick process and involves waiting for the support team to contact their "internal" team to increase the limits.

Also, it is key-specific so if the key expires, then the process will need to be restarted.

If others run into this and report it, I'm hoping they will decide to make this more configurable as this terraform provider is really not useful otherwise.

**Comment by sahaqaa** [comment]
> If others run into this and report it, I'm hoping they will decide to make this more configurable as this terraform provider is really not useful otherwise.

It depends on your use case and amount of resources that you have. Also it depends on the value of parallelism you run plan with. Do you run it with default parallelism value?

Could you please provide additional details?

**Comment by pickgr** [comment]
> > If others run into this and report it, I'm hoping they will decide to make this more configurable as this terraform provider is really not useful otherwise.
> 
> It depends on your use case and amount of resources that you have. Also it depends on the value of parallelism you run plan with. Do you run it with default parallelism value?
> 
> Could you please provide additional details?

Yes, I've been using the default parallelism value of 10, using 1 does seem to improve things.

For reference, I currently have 103 resources in my state. This will increase as we add more users, hosts and hopefully also start to manage access groups (when that is supported)

**Comment by sahaqaa** [comment]
Ok, got it. I will pass this information to our colleagues for review.

**Comment by pickgr** [comment]
> Hi Garret, 
>  
> Our team has looked into the issue you reported and found that the rate limit only applies to calls made through."connector/{id}/profile". 
>  
> Generating a connector profile is asynchronous, meaning the generation process starts when a user sends the first request. A 202 code is returned to all subsequent requests until the generation is complete. However, your client seems to retry the request without any pause, causing the burst capacity to be exhausted.
>  
> We recommend using a pause in between these calls to avoid such rate limits.
>  
> Still, we are working toward the improvement of how our endpoints manage these requests to avoid issues in the future.
> Kind Regards,
> 
> Gabriel Palmar
> Technical Support | OpenVPN Inc.

**Comment by chicco785** [comment]
i think the new go client implements some rate limiting which may help

**Comment by sahaqaa** [comment]
We've published new version of Terraform Provider to Registry: https://registry.terraform.io/providers/OpenVPN/cloudconnexa/latest

Going forward only https://registry.terraform.io/providers/OpenVPN/cloudconnexa/latest will be developed.

Please give new provider a try, hopefully it will fix your issue.

In case if problem persisst - please open new "Issue" (https://github.com/OpenVPN/terraform-provider-cloudconnexa/issues)

Sorry for inconvenience.
