### ISSUE TITLE
404 on existing networks

### ISSUE THREAD

**Issue by kacpercesarz98** [OpenVPN/terraform-provider-openvpn-cloud#133]
From yesterday I am getting 404 error on already existing networks created by terraform.
Planning failed. Terraform encountered an error while generating this plan.

```
Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: Status code: 404, Response body:
│
│   with openvpncloud_network.gcp-network,
│   on openvpn-cloud.tf line 1, in resource "openvpncloud_network" "gcp-network":
│    1: resource "openvpncloud_network" "gcp-network" {
│
╵
╷
│ Error: Status code: 404, Response body:
│
│   with openvpncloud_network.gcp-network-shared,
│   on openvpn-cloud.tf line 24, in resource "openvpncloud_network" "gcp-network-shared":
│   24: resource "openvpncloud_network" "gcp-network-shared" {
│
╵
```

**Comment by chicco785** [comment]
apparently APIs changed, if you fancy deploying a custom version, check out this pr for the time being: https://github.com/OpenVPN/terraform-provider-openvpn-cloud/pull/136

**Comment by sahaqaa** [comment]
@kacpercesarz98 we've published new version of Terraform Provider to Registry: https://registry.terraform.io/providers/OpenVPN/cloudconnexa/latest

It contains major breaking changes compared to https://registry.terraform.io/providers/OpenVPN/openvpn-cloud/latest

Going forward only https://registry.terraform.io/providers/OpenVPN/cloudconnexa/latest will be developed.

Please give new provider a try, hopefully it will fix your issue.
Sorry for inconvenience
