### ISSUE TITLE
Request for AccessGroup and Service Resources

### ISSUE THREAD

**Issue by unnirapido** [OpenVPN/terraform-provider-openvpn-cloud#14]
We would like to have resources to manage access groups and services. I see apis available for them [here](https://openvpn.net/cloud-docs/api-guide/)

`openvpncloud_service`
- This resource will allow to manage services with Terraform.
- api reference - https://openvpn.net/cloud-docs/api-guide/
<img width="773" alt="image" src="https://user-images.githubusercontent.com/106971228/208023369-3afa4c07-6abd-4b8f-9850-2e62bbabb171.png">

`openvpncloud_access_group`
- This resource will allow to manage access groups with Terraform.
- api reference - https://openvpn.net/cloud-docs/api-guide/
<img width="771" alt="image" src="https://user-images.githubusercontent.com/106971228/208023490-965e5e7f-6ef0-4e32-9347-365b252201b8.png">

**Comment by unnirapido** [comment]
@arslanbekov is there already a plan to add this? our team would be happy to contribute if needed

**Comment by arslanbekov** [comment]
Hey @unnirapido.
Right now, it's not in the plans. We will be glad to participate in this matter from your side.

**Comment by sahaqaa** [comment]
We've published new version of Terraform Provider to Registry: https://registry.terraform.io/providers/OpenVPN/cloudconnexa/latest

Going forward only https://registry.terraform.io/providers/OpenVPN/cloudconnexa/latest will be developed.

Please give new provider a try, hopefully it will fix your issue.

In case if problem persists - please open new "Issue" (https://github.com/OpenVPN/terraform-provider-cloudconnexa/issues)

Sorry for inconvenience.
