### ISSUE TITLE
Terraform Registry update for v0.1.0?

### ISSUE THREAD

**Issue by pickgr** [OpenVPN/terraform-provider-openvpn-cloud#144]
I noticed a new release was created by @arslanbekov arslanbekov last week:

https://github.com/OpenVPN/terraform-provider-openvpn-cloud/releases/tag/v0.1.0

but the official Terraform registry is still showing v0.0.11:

https://registry.terraform.io/providers/OpenVPN/openvpn-cloud/latest

and also includes the following:

> WARNING:
This provider is experimental and support for it is on a best-effort basis. Additionally, the underlying API for OpenVPN Cloud is on Beta, which means that future versions of the provider may introduce breaking changes. Should that happen, migration documentation and support will also be provided on a best-effort basis.

Are there plans to upgrade this?  Is v0.1.0 the best release to use now?

**Comment by arslanbekov** [comment]
Yes, the team @OpenVPN/cloudconnexa-terraform-project-admins is renaming the GitHub repository, terraform provider and creating a new release.

I think this will be resolved soon.

**Comment by sahaqaa** [comment]
@pickgr 
https://registry.terraform.io/providers/OpenVPN/openvpn-cloud/0.1.0 has major breaking changes compared to https://registry.terraform.io/providers/OpenVPN/openvpn-cloud/0.0.11

We've released Terraform Provider with correct name into Terraform Registry https://registry.terraform.io/providers/OpenVPN/cloudconnexa/latest

Going forward we advise to migrate to https://registry.terraform.io/providers/OpenVPN/cloudconnexa/latest
(and old one https://registry.terraform.io/providers/OpenVPN/openvpn-cloud will be depracated)
