### ISSUE TITLE
Problem using resource

### ISSUE THREAD

**Issue by claranobre** [OpenVPN/terraform-provider-openvpn-cloud#24]
I am getting the error 
` The provider openvpn/openvpn-cloud does not support resource type "openvpn-cloud_user". Did you mean "openvpncloud_user"?` in the documentation it indicates that I use the resource as the error informs, but when using it the provider does not recognize it because it cannot be found in the Terraform registry, the error follows:
```
Initializing provider plugins...
- Finding latest version of hashicorp/openvpncloud...
- Reusing previous version of hashicorp/tfe from the dependency lock file
- Reusing previous version of openvpn/openvpn-cloud from the dependency lock file
- Using previously-installed hashicorp/tfe v0.42.0
- Using previously-installed openvpn/openvpn-cloud v0.0.7
╷
│ Error: Failed to query available provider packages
│ 
│ Could not retrieve the list of available versions for provider hashicorp/openvpncloud: provider registry registry.terraform.io does not have a provider named registry.terraform.io/hashicorp/openvpncloud
```

**Comment by arslanbekov** [comment]
Hi @claranobre, it seems to be the same problem as here https://github.com/OpenVPN/terraform-provider-openvpn-cloud/issues/18

**Comment by aster-anto** [comment]
try mentioning the provider in OpenVPN cloud resources. Something like the following

` provider = openvpn-cloud`

**Comment by vladimir-kozyrev** [comment]
@claranobre please try `openvpncloud_user` instead of `openvpn-cloud_user`.

**Comment by sahaqaa** [comment]
We've published new version of Terraform Provider to Registry: https://registry.terraform.io/providers/OpenVPN/cloudconnexa/latest

Going forward only https://registry.terraform.io/providers/OpenVPN/cloudconnexa/latest will be developed.

Please give new provider a try, hopefully it will fix your issue.

In case if problem persists - please open new "Issue" (https://github.com/OpenVPN/terraform-provider-cloudconnexa/issues)

Sorry for inconvenience.
