### ISSUE TITLE
openvpncloud_route is not getting created but terraform apply is successful.

### ISSUE THREAD

**Issue by ykarakaya07** [OpenVPN/terraform-provider-openvpn-cloud#47]
used version 0.0.9
-------------------

Here is my code.

```
resource "openvpncloud_route" "frontend" {
  provider = openvpn-cloud
  network_item_id  = var.openvpncloud_network_id
  #description = "RXPlatform ${var.environment} frontend URL."
  type        = "DOMAIN"
  value       = "xyz.com"
}
```

**Comment by arslanbekov** [comment]
Hi @ykarakaya07, please attach the result of the Terraform execution.

**Comment by sahaqaa** [comment]
We've published new version of Terraform Provider to Registry: https://registry.terraform.io/providers/OpenVPN/cloudconnexa/latest

Going forward only https://registry.terraform.io/providers/OpenVPN/cloudconnexa/latest will be developed.

Please give new provider a try, hopefully it will fix your issue.

In case if problem persists - please open new "Issue" (https://github.com/OpenVPN/terraform-provider-cloudconnexa/issues)

Sorry for inconvenience.
