### ISSUE TITLE
Resource "openvpncloud_dns_record" not well documented

### ISSUE THREAD

**Issue by sahaqaa** [OpenVPN/terraform-provider-openvpn-cloud#83]
Hello,
I'm trying to understand what is "openvpncloud_dns_record" - i've checked file "resource_dns_record.go" and created resource:
```
resource "openvpncloud_dns_record" "name" {
  domain = "itc.ua" #required argument in documentation
  ip_v4_addresses = ["192.168.1.2"]
}
```
In "resource_dns_record.go" only 1 required field "domain" but when i tried to create resource "openvpncloud_dns_record" with only "domain" field -> i've received an error. So i had to add "ip_v4_addresses", after that resource was created.

But the main question - what this resource does? I created it via Terraform and then logged into UI, looked at every section, at all places -> and actually didn't found it anywhere in UI. What does this resources doing? How could it be used and where to find it in UI (after it was created in Terraform)?

Thank you.

**Comment by masseybradley** [comment]
The `openvpncloud_dns_record` resource creates DNS records in the "Settings" > "DNS" > "DNS Records".

![openvpncloud_dns_record](https://github.com/OpenVPN/terraform-provider-openvpn-cloud/assets/8556522/1c8abecd-cc23-4526-93a5-649b08abcf4b)

https://openvpn.net/cloud-docs/owner/servers/dns/adding-a-dns-record-for-a-private-domain-name.html

**Comment by sahaqaa** [comment]
@masseybradley Thanks. Also @garrettleber added description to this Resource in https://github.com/OpenVPN/terraform-provider-openvpn-cloud/pull/87

**Comment by sahaqaa** [comment]
No longer actual
